### PR TITLE
added preloaded State as an option to the getState factory

### PR DESCRIPTION
**Pull request by amrdraz**
This is referencing #57 

added test to one of the existing files though I think it should be in it's own file, didn't know where to place a test for a feature of getState

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey, very cool! Thank you for this!

There are two things I'd like to change in this PR before merging it:

* Could you move the test to its own `store.js` file?
* Could you add another test that uses a preloaded store, adds a logic store on it and renders the data to a React component (like in `logic-component.js`)... and then checks that the rendered data was what was preloaded to the state, and not what's in the reducer as the default value?

Thanks again! :)

**Comment by amrdraz** [comment]
done

*Amr Draz*
*Chief Technical Officer at DREIDEV*

*Mobile:* (+2) (01001132292)   |   *LinkedIn: *[Profile
<http://eg.linkedin.com/in/amrdraz>]

**Comment by amrdraz** [comment]
@mariusandra done

**Comment by mariusandra** [comment]
Wonderful, thank you! It's out with `0.27.2`

**Pull request merged**
